services:
  admin-dashy:
    image: lissy93/dashy:latest
    restart: unless-stopped
    networks:
      - t2_proxy
    volumes:
      - ${DOCKER_DIR}/appdata/admin-dashboard/config/dashy/conf.yml:/app/user-data/conf.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=t2_proxy"
      - "traefik.http.routers.admin-dashboard.rule=Host(`${ADMIN_DASHBOARD_HOST}`)"
      - "traefik.http.routers.admin-dashboard.entrypoints=https"
      - "traefik.http.routers.admin-dashboard.tls=true"
      - "traefik.http.routers.admin-dashboard.middlewares=chain-authentik@file"
      - "traefik.http.services.admin-dashboard.loadbalancer.server.port=8080"

networks:
  t2_proxy:
    external: true
